#
# This bashrc will source files from any profilerc directories
# linked into users home.
#
# Unique configuration for different profiles should be placed
# in that profiles respective profilerc directory.
#
# For example, default will contain the directory .profilerc_default
# with any files that should be sourced within it.
#
for profilerc in $(ls -d ~/.profilerc_*/*); do
    echo "Sourcing profilerc file '$profilerc'."
    source $profilerc
done
